sous-chefs/redisio

- README.md
this cookbook needs both ulimit and build-essential, so update docu to reflect that
> update readme to reflect both dependancies

- README.md
A few of the redisio[] attributes were missing backticks for the code spans
> minor markdown formatting in README.md

- .kitchen.yml
- Berksfile
- README.md
- attributes/default.rb
- providers/configure.rb
- providers/install.rb
- providers/sentinel.rb
- recipes/configure.rb
- recipes/default.rb
- recipes/install.rb
Hi,
First, thanks for your cookbook.
In your cookbook, the only way to install Redis is through tarballs. For production usage, it's better to not install all dependencies, recompile on production server, etc...
That's why I added the packaging support. It requires additional repositories to get the latest version (as described in the .kitchen.yml and Berksfile) but is not directly managed by the cookbook as it's not its role.
I kept the way you managed multi tenancies through init/upstart scripts.
Can you please merge this PR.
Thanks in advance
> feat: adding package installation support

- README.md
Change occurred in [2.1.0](https://github.com/brianbianco/redisio/blob/master/changelog.md#210--) but readme was not updated.
> Update default mirror in README.md

- .kitchen.yml
- providers/configure.rb
- templates/default/redis.conf.erb
- test/integration/default/serverspec/redisio_spec.rb
Fixes #166.
- Allow 'save' to be anything that responds to `.each`. If it responds to `.each_line`, we unwrap that.
- Add a test to be sure backwards compatible 'string' works for the save attribute.
- Make .kitchen.yml redis instances be easier YAML syntax for array-of-hashes
> Allow instance 'save' to be string or array

- metadata.rb
source_url and issues_url are Chef 12 and not backwards compatible.
> Fix to run under Chef <12

- attributes/default.rb
- metadata.rb
Fix cluster settings, because they differs at providers/ and attributes/. If setting up `cluster-enabled`, nothing happens, because providers expect to have `clusterenabled`.
> Fix cluster settings, because they differs at providers/ and attributes/

- .kitchen.yml
- README.md
- providers/sentinel.rb
- recipes/sentinel.rb
- templates/default/sentinel.conf.erb
- test/integration/helpers/serverspec/sentinel_examples.rb
- test/integration/multisentinel/serverspec/multiple_sentinels_spec.rb
- test/unit/spec/sentinel_spec.rb
- Add support in sentinel resource for an array of masters to monitor, with backwards compatibility for the older attributes, fixes #73. Replaces #87.
- Introduce a test-kitchen test for sentinel watching multiple masters.
- Incidentally, fixes #193 as well, since it adds a master name attribute for each master.
> Monitor multiple masters with single sentinel

- .kitchen.yml
- attributes/default.rb
RE: #177.
- Add package support for ubuntu family, with slightly different package name
- Add platform ubuntu 14.04 to our test suites, allow package method to be tested on 14.04
> Add support for Ubuntu via package install

- providers/configure.rb
`default["redisio"]["default_settings"]["ulimit"]` attribute set `nil`,  but it would have been made `/etc/security/limits.d/redis_limits.conf`
`user_ulimit` is  `definition`, not `lwrp`. 
ref: https://github.com/bmhatfield/chef-ulimit/blob/master/definitions/user_ulimit.rb
Chef definition does not support nof_if/only_if.
> Fix bug. not valid `only_if` of `user_ulimit`

- providers/sentinel.rb
If I'm seeing this right the sanity would never fail.
> Fix sentinel instance required params sanity.

- README.md
- attributes/default.rb
- providers/configure.rb
- templates/default/redis.conf.erb
Add an attribute, `rename_command', that accepts a hash of old => new
name translations.
> Support rename_command stanzas in redis.conf

- README.md
- attributes/redis_sentinel.rb
- providers/configure.rb
- providers/sentinel.rb
> Only create the sentinel config files once

- providers/configure.rb
- providers/sentinel.rb
`current['configdir']` could be ephemeral
> Breadcrumb file should be in the config dir not data dir

- templates/default/redis.conf.erb
they were introduced after redis 2.8.0.
now works on Ubuntu 14.04 (redis 2.8.4)
ref: #239
> fix some new 2.8 directives

- recipes/install.rb
Currently `node['redisio']['version']` is only used for tar installs.  It should be available for package installs as well.
> Allow version to be specified for pacakge install

- providers/install.rb
We want to subscribe to the installation resource to restart Redis when a new version is installed, but currently the cookbook indicates that the installation resource is updated every time it's run. This PR changes the behavior to only indicate the resource has been updated when installation actually takes place.
> Only indicate install resource is updated when installation occurs

- templates/default/redis.conf.erb
Pull request for #257. I used https://github.com/antirez/redis/blob/5ac5e3ebd7da8f041ebd7c4d20020208a3066b2d/redis.conf as a reference.
> #257 - Fixes spelling and grammar mistakes in reds.conf.erb.

- recipes/install.rb
This prevented `false` from ever making it into the install resource, which defaults to `true`
The default is set here https://github.com/brianbianco/redisio/blob/master/resources/install.rb#L30
> Allow disabling safe_install in the install recipe

- .kitchen.yml
- README.md
- attributes/default.rb
- attributes/redis_sentinel.rb
- providers/configure.rb
- providers/install.rb
- providers/sentinel.rb
- recipes/configure.rb
- recipes/sentinel.rb
- templates/default/redis.conf.erb
- templates/default/redis.rcinit.erb
- templates/default/sentinel.conf.erb
- templates/default/sentinel.rcinit.erb
- test/integration/default/serverspec/redisio_spec.rb
- test/integration/helpers/serverspec/redisio_examples.rb
- test/integration/helpers/serverspec/sentinel_examples.rb
- test/integration/multisentinel/serverspec/multiple_sentinels_spec.rb
Hi,
I added FreeBSD-10.3 support and would be great if it could be part of the official redisio cookbook.
2 caveats: 
- installation from source is not supported because it would add a lot of extra dependencies for portsnap/portmaster and portsnap-downgrade
- setting ulimits is not supported because v0.1.2 of the ulimit cookbook is incompatible with FreeBSD (expects group 'root')
> Added FreeBSD-10.3 support

- recipes/_install_prereqs.rb
On non-debian and non-rhel platforms this fixes nil exception when installing sentinel
> default packages_to_install to empty array 

- templates/default/redis.conf.erb
the existing comment is from redis 2.6, which didn't allow multiple addresses. That's a bit confusing, so take the documentation from 3.0.
> update 'bind' config comments

- README.md
- metadata.rb
- recipes/disable_os_default.rb
When using redis from the ubuntu package, i use this simple recipe to disable the default OS init script.
Otherwise i can't use the init script provided by this recipe after a reboot.
Do you think something like this can be a useful addition?
> add disable_os_default recipe

- providers/configure.rb
I spent a bit trying to figure out why setting config['ulimit'] was capping out at 10k (max_clients).  This fixes that, which lets someone control ulimits on the redis user while protecting against too small of a ulimit.
> use the config's ulimits if set and is > max_clients.

- libraries/redisio.rb
version could be like 2:3.0.6-rwky1~trusty and must be detected properly for including parts of configuration (vm-enable)
> fix version detection with epoch version numbers from deb/ubuntu 

- templates/default/redis.conf.erb
…d .empty? for NilClass]
Switching the order of the test from:
```ruby 
v.empty? || v.nil? 
``` 
to this:
```ruby
v.nil? || v.empty?
``` 
Will fix the problem
> rename_commands should be checked for nil before empty

- attributes/default.rb
- providers/configure.rb
- templates/default/redis.conf.erb
This is useful when using sentinel and redis together with several slaves
- min-slaves-to-write (config attribute `minslavestowrite`)
- min-slaves-max-lag (config attribute `minslavesmaxlag`)
> Add min-slaves redis options

- templates/default/redis.init.erb
I made a modification to allow redis init to start even if the app was crashed.
Current behaviour: System or user sigkill the app ( -9 ), then the init was only trusting if the pid exist or not, but because sigkill doesn't notify the process to be killed, the pid will remain, so the init will not allow you to start unless you remove the PID.
This is very useful in case the system kills REDIS by excess of memory.
> Allow /etc/init start after sigterm from system or user

- providers/configure.rb
- providers/sentinel.rb
`node['etc']['passwd']` is only refreshed by Ohai at the start of each Chef run so if the user is created earlier in the same run or if the Ohai plugin is disabled then this check blows up.
The check was going to be removed altogether according to #252 but I would not like this to happen. I would like to create a Redis instance under the same user that I have already set up for a different service. I imagine that's why the `not_if` was put there in the first place. This change deals with the main complaint of #252 (and also #296) but if you like, I could create an attribute such as `create_user` for this instead.
> Check user existence with Etc, not ohai node attributes

- README.md
- attributes/default.rb
- providers/configure.rb
- recipes/configure.rb
- recipes/enable.rb
- templates/default/redis@.service.erb
This fixes Debian/Ubuntu, fixes shutdowns with UNIX sockets, deals with multiple instances, and more.
It fixes #271 and #283. It supersedes #274.
> Various systemd-related improvements

- recipes/sentinel.rb
- recipes/sentinel_enable.rb
> Fix systemd paths for sentinel service

- README.md
This brings the cluster configuration options in line with the way they're defined in the template.
> Fix cluster options in README

- providers/configure.rb
> Fix systemd loader to use descriptors instead of max_clients+32

- .kitchen.yml
- .travis.yml
- templates/default/redis.conf.erb
Closes https://github.com/brianbianco/redisio/issues/336
> Fix Redis 2.4.x config

- providers/configure.rb
- providers/install.rb
- providers/sentinel.rb
Minor changes to fix Chef 13 compatibility issues.
> Chef 13 compatibility

- templates/default/sentinel.conf.erb
There is a typo in the sentinel configuration where the announce port is incorrectly being included as the announce IP.
> Use correct `announce-port` directive

- .kitchen.dokken.yml
- .kitchen.yml
- .rubocop.yml
- Berksfile
- Cheffile
- Gemfile
- Rakefile
- Thorfile
- Vagrantfile
- changelog.md
- libraries/redisio.rb
- metadata.rb
- providers/configure.rb
- providers/sentinel.rb
- test/unit/spec/sentinel_spec.rb
- test/unit/spec/spec_helper.rb
This is a breaking change and should be a major version release as we drop support for `chef` versions less than `13.3`.
There is more cleanup work to do but this is a good first step.
Signed-off-by: Ben Abrams <me@benabrams.it>
> some much needed cleanup and CI fixes

- metadata.rb
As stated in #393, this cookbook requires at least version 2.2.0 and above of
the selinux_policy cookbook. This should resolve #393.
Describe what this change achieves
List any existing issues this PR resolves
> Update to use selinux_policy >= 2.2.0 which includes selinux_policy_install

- CHANGELOG.md
- templates/default/redis.conf.erb
This change will properly run blocks in the redis.conf.erb template file when checking for redis version "X and higher"
https://github.com/sous-chefs/redisio/issues/427
- [ x ] All tests pass. See TESTING.md for details.
> Properly version check when needed in redis.conf template

- CHANGELOG.md
- recipes/disable.rb
71469215 introduced systemd support, which uses a slightly different
service naming convention (ie. redis@6379 vs redis6379), and updated the
enable recipe to conditionally use the right service name, however the
disable recipe wasn't updated to match, thus leading to using the wrong
service name when using systemd, leading to an unknown service.
I didn't see any tests around the disable recipe, so I wasn't sure on where to start to add new ones.
> Fix disable recipe service naming for systemd

- CHANGELOG.md
- README.md
- attributes/redis_sentinel.rb
- kitchen.yml
- providers/sentinel.rb
- templates/default/sentinel.conf.erb
This would allow users to configure protected mode option in sentinel configuration file.
https://github.com/antirez/redis/blob/5.0.5/sentinel.conf#L17
https://github.com/sous-chefs/redisio/issues/387
> Add protected mode to sentinel configuration file

- CHANGELOG.md
- providers/configure.rb
It changes the configdir group to `redis` instead of `root` and the write permission to that group.
#450
> Fixes configdir permissions (Closes #450)

- CHANGELOG.md
- providers/configure.rb
providers/configure.rb was still calling resources from the selinux_policy cookbook, which was deprecated in 6.0.0 causing cinc-client runs to die with NoMethodError
List any existing issues this PR resolves
> Remove references to selinux_policy cookbook

- CHANGELOG.md
- templates/default/redis.conf.erb
Version check fix to unlock some settings for Redis v4+.
Currently settings like `tcpbacklog` are skipped for Redis version 4 and above.
> fix: unlock some settings for Redis v4+

- CHANGELOG.md
- README.md
- attributes/redis_sentinel.rb
- providers/sentinel.rb
- templates/default/sentinel.conf.erb
Adding `maxclients` option to Sentinel configuration file.
Currently there's no way to set `maxclients` for Sentinel instances.
> Add maxclients option to sentinel config file

- CHANGELOG.md
- README.md
- attributes/default.rb
- providers/configure.rb
- templates/default/redis.conf.erb
Adding `aclfile` option to Redis configuration file.
Enables configuring external ACL file for Redis v6+
> add option to set aclfile

- CHANGELOG.md
- README.md
- attributes/redis_sentinel.rb
- providers/sentinel.rb
- templates/default/sentinel.conf.erb
Adding aclfile option to Sentinel configuration file.
Enables configuring external ACL file for Redis Sentinel v6+
> Sentinel: add option to set aclfile

- CHANGELOG.md
- README.md
- attributes/redis_sentinel.rb
- providers/sentinel.rb
- templates/default/sentinel.conf.erb
Add `includes` option to Sentinel configuration file.
Currently, there's no way to include custom config files into Sentinel config.
> Add includes option to sentinel config file

- CHANGELOG.md
- README.md
- attributes/default.rb
- providers/configure.rb
- templates/default/redis.conf.erb
Currently, there's no way to specify custom `cluster-port` value. Adding this option to the configuration file.
No related issues.
> Add cluster-port option to redis config file
