README.md
=> Fix configuration sample code syntax.

templates/default/redis.conf.erb
add conditions for redis version 3
=> Redis v3 - change conditions

providers/install.rb
This fixes an issue when using this cookbook with vagrant-cachier and nfs.
=> Fixes a permission issue with the tarball and nfs

recipes/install.rb
=> Only specify particular attributes if a non nil value is provided

README.md, attributes/default.rb, attributes/redis_sentinel.rb, providers/configure.rb, providers/sentinel.rb, recipes/configure.rb, recipes/sentinel.rb, templates/default/redis-sentinel@.service, templates/default/redis@.service.erb, templates/default/sentinel.conf.erb
- Add encyrpted data bag support
- Fix sysmtemd nofile limit (systemd does not honor `/etc/security/limits.d/` files)
- Add announce-ip and announce-port directives for sentinel
Verified as working in a test env
=> Add encyrpted data bag support, fix systemd, add announce directives

attributes/default.rb, providers/configure.rb, templates/default/redis.conf.erb
Add protected-mode option as optional.
@brianbianco
=> Add protected-mode option as optional

.kitchen.yml, README.md, changelog.md, metadata.rb
To close #290 - 
- Update changelog.md to reflect changes since previous release.
- Update version number in metadata and README
- Minor bugfix - added missing `end` in .kitchen.yml
=> Release 2.5.0

.travis.yml, Gemfile, README.md
Note: needs travis to be enabled on the repo
Closes https://github.com/brianbianco/redisio/issues/187
=> Add Travis config

.rubocop.yml, .travis.yml, Gemfile, Rakefile, providers/configure.rb, providers/sentinel.rb, resources/configure.rb, templates/default/sentinel.conf.erb
Move 1st kitchen require into the begin block so that the require exception is caught in CI testing and ignored.
=> Fix TravisCI builds

.kitchen.yml, README.md, Vagrantfile, attributes/redis_sentinel.rb, metadata.rb, providers/sentinel.rb, templates/default/sentinel.conf.erb, test/unit/spec/sentinel_spec.rb
Useful, if you have more than one sentinel
=> Add sentinel_bind to bind sentinel to different IPs

attributes/default.rb, providers/configure.rb
Carries https://github.com/brianbianco/redisio/pull/178
=> Make source of redis.conf template configurable

README.md, attributes/redis_sentinel.rb, providers/sentinel.rb, recipes/sentinel.rb, resources/sentinel.rb, templates/default/sentinel.conf.erb
Carries https://github.com/brianbianco/redisio/issues/190
=> Support sentinel notification-script and client-reconfig-script

.travis.yml, templates/default/redis.conf.erb
Closes https://github.com/brianbianco/redisio/issues/337
=> Restrict aof-load-truncated to redis 3+

CHANGELOG.md, providers/configure.rb, test/unit/spec/spec_helper.rb
More cookstyle fixes with the latest cookstyle
Signed-off-by: Tim Smith <tsmith@chef.io>
=> Cookstyle fixes

.rubocop.yml
Describe what this change achieves
List any existing issues this PR resolves
=> Error: The  cop has been renamed to .

recipes/default.rb
=> Pull the disable_os_default recipe from the default one

CHANGELOG.md, attributes/default.rb, attributes/redis_gem.rb, attributes/redis_sentinel.rb, libraries/redisio.rb, metadata.rb, providers/configure.rb, providers/install.rb, providers/sentinel.rb, recipes/_install_prereqs.rb, recipes/configure.rb, recipes/default.rb, recipes/disable.rb, recipes/disable_os_default.rb, recipes/enable.rb, recipes/install.rb, recipes/redis_gem.rb, recipes/sentinel.rb, recipes/sentinel_enable.rb, resources/configure.rb, resources/install.rb, resources/sentinel.rb
Hey!
I ran Cookstyle 7.24.1 against this repo and here are the results.
This repo was selected due to the topics of chef-cookbook
- 74:40 refactor: `Chef/Modernize/UseChefLanguageSystemdHelper` - Chef Infra Client 15.5 and later include a `systemd?` helper for checking if a Linux system uses systemd. (https://docs.chef.io/workstation/cookstyle/chef_modernize_usecheflanguagesystemdhelper)
=> Automated PR: Cookstyle Changes

CHANGELOG.md, attributes/default.rb, files/sudo, metadata.rb, recipes/configure.rb, recipes/default.rb, recipes/install.rb, recipes/sentinel.rb, recipes/ulimit.rb, resources/configure.rb, resources/install.rb, resources/sentinel.rb, templates/default/domain.erb, templates/default/su.erb, templates/default/ulimit.erb
- unified-mode for Chef 17 compatability
- stop depending on selinux_policy
- stop depending on the ulimits cookbook
I plan to remove the ulimit config in a future release as I feel this is out of scope, and most people don't configure it. 
We should have an example of how to use it though!
=> Unfied mode, enable!

.delivery/project.toml, .github/workflows/ci.yml, .overcommit.yml, CHANGELOG.md
This PR will standardise the files we have with out agreed spec in sous-chefs/repo-management.
This repo has been identified by topic(s) of chef-cookbook
=> Automated PR: Standardising Files

CHANGELOG.md, templates/default/redis@.service.erb
Fixes listening on only loopback interface
https://github.com/sous-chefs/redisio/issues/439
=> update redis@ service template

CHANGELOG.md, kitchen.yml, providers/configure.rb, providers/sentinel.rb
Makes the redisio `configure` resource idempotent.
It's helpful to hide whitespace when reviewing diffs.
#215
=> Make the redisio `configure` resource idempotent
